"""post subjects

Revision ID: 7a49b3d1de7b
Revises: e3ffc21bc5d4
Create Date: 2025-04-20 20:31:35.630431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a49b3d1de7b'
down_revision = 'e3ffc21bc5d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
